/**
 * Test-only stub for the Vite virtual module `virtual:pwa-register`.
 *
 * In production this module is generated by `vite-plugin-pwa` and exposes
 * `registerSW`, which sets up the service worker lifecycle. Vitest cannot
 * resolve the virtual module on its own, so `vitest.config.ts` aliases
 * `virtual:pwa-register` to this file.
 *
 * Tests that need to assert against the SW lifecycle should use
 * `vi.mock('virtual:pwa-register', ...)` to override this default.
 */
export function registerSW(_options?: {
  immediate?: boolean;
  onNeedRefresh?: () => void;
  onOfflineReady?: () => void;
}): (reloadPage?: boolean) => Promise<void> {
  return async () => {};
}
